/*
Covid 19 Data Exploration 
Skills used: Joins, CTE's, Temp Tables, Windows Functions, Aggregate Functions, Creating Views, Converting Data Types
*/

--SELECT DATA THAT WE WILL BE USING
SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL AND LOCATION LIKE  'Canada'
ORDER BY 1,2
limit 10;

--TOTAL CASES VS. TOTAL DEATHS
--Shows the likelihood of dying if you contract the disease in your country
SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)*100 AS DEATH_PERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL AND LOCATION LIKE  'India'
ORDER BY 1,2;

--TOTAL CASES VS. TOTAL POPULATION

SELECT LOCATION, DATE, POPULATION, TOTAL_CASES, (TOTAL_CASES/POPULATION)*100 AS PERCENTPOPULATIONINFECTED
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL AND LOCATION LIKE  'India'
ORDER BY 1,2;

--COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION
SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) HIGHESTINFECTIONCOUNT, MAX((TOTAL_CASES/POPULATION))*100 AS PERCENTPOPULATIONINFECTED
FROM COVID_DEATHS
--WHERE CONTINENT IS NOT NULL AND LOCATION LIKE  'India'
GROUP BY LOCATION, POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC;

 --COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION
SELECT LOCATION, MAX(TOTAL_DEATHS) AS TOTALDEATHCOUNT
FROM COVID_DEATHS
GROUP BY LOCATION
HAVING MAX(TOTAL_DEATHS)>0
ORDER BY TOTALDEATHCOUNT DESC;

--CONTINENTS WITH HIGHEST DEATH COUNT PER POPULATION
SELECT CONTINENT, MAX(TOTAL_DEATHS) AS TOTALDEATHCOUNT
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
HAVING MAX(TOTAL_DEATHS)>0
ORDER BY TOTALDEATHCOUNT DESC;

--GLOBAL NUMBERS

SELECT SUM(NEW_CASES) AS TOTALCASES, SUM(NEW_DEATHS) AS TOTALDEATHS, SUM(NEW_DEATHS)/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
--GROUP BY DATE
ORDER BY 1,2;


--TOTAL POPULATION VS. NUMBER OF VACCINATIONS BY DATE
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS
FROM COVID_DEATHS DEA,
COVID_VACS VAC
WHERE DEA.LOCATION=VAC.LOCATION
AND DEA.DATE=VAC.DATE
AND DEA.CONTINENT IS NOT NULL
ORDER BY 2,3;

--TOTAL POPULATION VS. TOTAL VACCINATIONS PER COUNTRY
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS,
SUM(VAC.NEW_VACCINATIONS) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVID_DEATHS DEA,
COVID_VACS VAC
WHERE DEA.LOCATION=VAC.LOCATION
AND DEA.DATE=VAC.DATE
AND DEA.CONTINENT IS NOT NULL
--AND DEA.LOCATION = 'Canada'
ORDER BY 2,3;

--USING CTE TO FIND THE TOTAL PERCENTAGE OF POPULATION VACCINATED IN A COUNTRY

WITH POPVSVACS(CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLINGPEOPLEVACCINATED)
AS (
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS,
SUM(VAC.NEW_VACCINATIONS) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVID_DEATHS DEA,
COVID_VACS VAC
WHERE DEA.LOCATION=VAC.LOCATION
AND DEA.DATE=VAC.DATE
AND DEA.CONTINENT IS NOT NULL
--AND DEA.LOCATION = 'Canada'
--ORDER BY 2,3;
)
SELECT *, (ROLLINGPEOPLEVACCINATED/POPULATION) AS PERCENTPOPULATIONVACCINATED
FROM POPVSVACS;

--USING TEMPTABLES TO FIND THE TOTAL PERCENTAGE OF POPULATION VACCINATED IN A COUNTRY

CREATE TABLE PERCENTPOPULATIONVACCINATED
AS
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS,
SUM(VAC.NEW_VACCINATIONS) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVID_DEATHS DEA,
COVID_VACS VAC
WHERE DEA.LOCATION=VAC.LOCATION
AND DEA.DATE=VAC.DATE
AND DEA.CONTINENT IS NOT NULL
--AND DEA.LOCATION = 'Canada'
ORDER BY 2,3;

SELECT *, (ROLLINGPEOPLEVACCINATED/POPULATION) AS PERCENTPOPULATIONVACCINATED
FROM PERCENTPOPULATIONVACCINATED;

--CREATING A VIEW TO STORE DATA FOR LATER VISUALISATIONS

CREATE VIEW TOTAL_VACS_BY_DATE
AS
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS,
SUM(VAC.NEW_VACCINATIONS) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVID_DEATHS DEA,
COVID_VACS VAC
WHERE DEA.LOCATION=VAC.LOCATION
AND DEA.DATE=VAC.DATE
AND DEA.CONTINENT IS NOT NULL
--AND DEA.LOCATION = 'Canada'
ORDER BY 2,3;

ALTER TABLE COVID_VACS ALTER COLUMN NEW_VACCINATIONS TYPE FLOAT;